[package]
name = "rustzen-config"
version = "0.5.0"
edition = "2024"
license.workspace = true
publish = false

[features]
default = ["admin", "insights", "monitor-controller", "monitor-agent", "reports"]
admin = []
admin-monitor = []
insights = []
monitor-controller = []
monitor-agent = []
reports = []

[dependencies]
dotenvy = "0.15"
figment = { version = "0.10.19", features = ["env"] }
rustzen-runtime = { path = "../runtime" }
serde = { version = "1", features = ["derive"] }
url = "2"
