import { expect, test } from "bun:test";
import { rm } from "node:fs/promises";
import { createExport, releaseVersion, sourceIdentity } from "./container-export-test-fixture.ts";
import { verifyAnalyticsContainerExport } from "./container-export-validator.ts";
import { analyticsContainerCommands, verifyAnalyticsContainerContractReceipt } from "./analytics-container-contract-receipt.ts";
import { canonicalJson, sha256 } from "./release-manifest-core.ts";

test("Analytics receipt binds owner and protocol wire outputs", async () => {
 const selection={schemaVersion:1,preset:"analytics",target:"x86_64-unknown-linux-musl"}; const root=await createExport(selection,{evidence:"linux-amd64-buildkit"});
 try { const snapshot=await verifyAnalyticsContainerExport(root,selection,sourceIdentity,releaseVersion), m=snapshot.manifest(),p=snapshot.recordedProvenance(); const api=JSON.parse(new TextDecoder().decode(snapshot.artifact("release/contracts/api/api.json").bytes)), config=JSON.parse(new TextDecoder().decode(snapshot.artifact("release/contracts/config/config.json").bytes)), protocol=JSON.parse(new TextDecoder().decode(snapshot.artifact("release/contracts/protocol/protocol.json").bytes)); const descriptor=protocol.descriptor??canonicalJson(protocol), wire=`${descriptor}\n${sha256(descriptor)}\n`; const out=[api.owners.admin,api.owners.insights,config.owners.access,config.owners.insights].map(x=>`${canonicalJson(x)}\n`).concat([wire,wire]); const paths=["release/contracts/api/api.json","release/contracts/api/api.json","release/contracts/config/config.json","release/contracts/config/config.json","release/contracts/protocol/protocol.json","release/contracts/protocol/protocol.json"]; const receipt:any={schemaVersion:1,kind:"analytics-container-contract-receipt",context:{dockerContext:"default",platform:"linux/amd64"},commands:analyticsContainerCommands.map((command,i)=>({command:[...command],stdoutSha256:sha256(out[i]),artifactPath:paths[i],artifactSha256:sha256(snapshot.artifact(paths[i]).bytes)})),sourceIdentity:{before:sourceIdentity,after:sourceIdentity},manifestSha256:sha256(canonicalJson(m)),provenanceSha256:sha256(canonicalJson(p)),verifierImageDigest:`sha256:${"a".repeat(64)}`,restrictions:{network:"none",readOnlyRootfs:true,tmpfs:"noexec,nosuid,nodev",capDrop:"ALL",noNewPrivileges:true,pids:32,memory:"256m"},runtime:false,certificate:false,signing:false,installer:false,browser:false,load:false}; expect(verifyAnalyticsContainerContractReceipt(snapshot,receipt,out)).toEqual(receipt); for(const f of [(x:any)=>x.commands.pop(),(x:any)=>x.sourceIdentity.after="x",(x:any)=>x.restrictions.pids=3,(x:any)=>x.runtime=true,(x:any)=>x.commands[0].stdoutSha256="0".repeat(64),(x:any)=>x.manifestSha256="0".repeat(64),(x:any)=>{delete x.runtime},(x:any)=>{x.commands[1].extra=1}]){const x=structuredClone(receipt);f(x);expect(()=>verifyAnalyticsContainerContractReceipt(snapshot,x,out)).toThrow();} } finally { await rm(root,{recursive:true,force:true}); }
});
