# docker-compose.yml
# 用于本地开发环境的服务编排

version: "3.8"

services:
  # 后端应用服务
  app:
    # 使用当前目录下的 Dockerfile 进行构建
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # 将容器的 8000 端口映射到主机的 8000 端口
    ports:
      - "8000:8000"
    # 挂载代码目录，实现热重载 (需要后端支持)
    # 注意：对于编译型语言，热重载需要在容器内运行 watch 工具
    volumes:
      - ../backend:/app/backend
      - ../frontend:/app/frontend
    # 引用 .env 文件中的环境变量
    env_file:
      - ../.env.example
    # 依赖于数据库服务，确保数据库先启动
    depends_on:
      - db
    # 自定义容器启动命令，以支持开发模式下的热重载
    # 例如：CMD ["cargo", "watch", "-x", "run"]
    # 默认使用 Dockerfile 中的 CMD

  # 数据库服务
  db:
    image: postgres:16-alpine
    # 引用 .env 文件中的环境变量
    env_file:
      - ../.env.example
    # 将数据库的数据持久化到本地 volume，防止容器重启后数据丢失
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  # 定义一个 volume 用于持久化数据库数据
  postgres_data:
