import { parseMonitorLoadEvidence } from "./monitor-load-admission.ts";
import { isAbsolute, resolve } from "node:path";
const obj=(x:unknown):x is Record<string,any>=>Boolean(x)&&typeof x==="object"&&!Array.isArray(x), exact=(x:unknown,k:string[])=>obj(x)&&JSON.stringify(Object.keys(x).sort())===JSON.stringify(k), int=(x:unknown)=>Number.isSafeInteger(x)&&Number(x)>=0, hash=/^[a-f0-9]{64}$/;
const names=["lane-1","drain-1","quiet-1","lane-2","drain-2","quiet-2","fault","recovery"];
const same=(a:any,b:any)=>a.pid===b.pid&&a.dev===b.dev&&a.ino===b.ino&&a.sha256===b.sha256;
const owner=(x:unknown)=>exact(x,["dev","ino","pid","sha256"])&&int((x as any).pid)&&(x as any).pid>1&&typeof (x as any).dev==="string"&&typeof (x as any).ino==="string"&&hash.test((x as any).sha256);
const events=(x:unknown)=>exact(x,["memory.events.max","memory.events.oom","memory.events.oom_kill","memory.max","pids.events.max"])&&Object.values(x as any).every(int);
const reading=(x:unknown)=>exact(x,["at","events","hwm","memoryCurrent","memoryPeak","pidsCurrent","pidsPeak","rss"])&&["at","hwm","memoryCurrent","memoryPeak","pidsCurrent","pidsPeak","rss"].every(k=>int((x as any)[k]))&&events((x as any).events)&&(x as any).pidsCurrent<=64&&(x as any).memoryPeak<=384*1024*1024;
const rank=(v:number[],p:number)=>[...v].sort((a,b)=>a-b)[Math.ceil(v.length*p)-1];
export const validatePhase=(x:unknown,index:number)=>{
    if(!exact(x,["name","services","snapshots","workDurationMs"]))throw Error("monitor load phase differs"); const p=x as any,s=p.snapshots;
    if(p.name!==names[index]||!int(p.workDurationMs)||!Array.isArray(s)||s.length!==2||s.some((r:any)=>!reading(r))||s[0].at>=s[1].at||s[1].at-s[0].at<p.workDurationMs||!exact(p.services,["after","before"])||!exact(p.services.before,["admin","monitor"])||!exact(p.services.after,["admin","monitor"])||!owner(p.services.before.admin)||!owner(p.services.before.monitor)||!owner(p.services.after.admin)||!owner(p.services.after.monitor))throw Error("monitor load phase differs");
    if(index===6){if(!same(p.services.before.admin,p.services.after.admin)||same(p.services.before.monitor,p.services.after.monitor)||p.services.before.monitor.dev!==p.services.after.monitor.dev||p.services.before.monitor.ino!==p.services.after.monitor.ino||p.services.before.monitor.sha256!==p.services.after.monitor.sha256)throw Error("monitor load fault identity differs");}else if(!same(p.services.before.admin,p.services.after.admin)||!same(p.services.before.monitor,p.services.after.monitor))throw Error("monitor load phase identity differs"); return p;
};
const inventory=(x:unknown,n:number,label:string)=>{if(!obj(x)||Object.entries(x).length!==n||Object.entries(x).some(([p,d])=>!isAbsolute(p)||resolve(p)!==p||!hash.test(String(d))))throw Error(`monitor load ${label} differs`);};
const maxima=(r:any[])=>({rss:Math.max(...r.map(x=>x.rss)),hwm:Math.max(...r.map(x=>x.hwm)),pidsPeak:Math.max(...r.map(x=>x.pidsPeak)),memoryCurrent:Math.max(...r.map(x=>x.memoryCurrent)),memoryPeak:Math.max(...r.map(x=>x.memoryPeak))}), sameRecord=(a:any,b:any)=>exact(a,Object.keys(b).sort())&&Object.keys(b).every(k=>obj(b[k])?sameRecord(a[k],b[k]):a[k]===b[k]);
const assertSeries=(v:any[])=>{for(let i=1;i<v.length;i++)if(v[i]<v[i-1])throw Error("monitor load cumulative resource differs");};
/** Strict P8g receipt admission: each phase has exactly two cumulative snapshots. */
export function parseMonitorLoadReceipt(value:unknown){
 const r=parseMonitorLoadEvidence(value) as any; inventory(r.inputs,8,"inputs");inventory(r.p8eSidecars,12,"P8e sidecars");
 if(!exact(r.selection,["artifactClass","buildId","compositionId","preset","target"])||r.selection.preset!=="monitor"||r.selection.target!=="x86_64-unknown-linux-musl"||r.selection.artifactClass!=="server"||!exact(r.initialServices,["admin","monitor"])||!owner(r.initialServices.admin)||!owner(r.initialServices.monitor)||!exact(r.corpus,["disksPerNode","nodes","sentinel"])||r.corpus.nodes!==100||r.corpus.disksPerNode!==4||typeof r.corpus.sentinel!=="string")throw Error("monitor load identity differs");
 const phases=r.phases.map(validatePhase), all=phases.flatMap((p:any)=>p.snapshots);if(JSON.stringify(phases.map((p:any)=>p.name))!==JSON.stringify(names)||phases.some((p:any,i:number)=>i&&phases[i-1].snapshots[1].at>p.snapshots[0].at))throw Error("monitor load phase order differs");
 let previous=r.initialServices;for(const [i,p] of phases.entries()){if(!same(previous.admin,p.services.before.admin)||!same(previous.monitor,p.services.before.monitor))throw Error("monitor load owner chain differs"); if(!same(r.initialServices.admin,p.services.after.admin))throw Error("monitor load admin identity differs");previous=p.services.after;if(i!==6&&!same(p.services.before.monitor,p.services.after.monitor))throw Error("monitor load monitor identity differs");}
 for(const key of ["memoryPeak","pidsPeak"])assertSeries(all.map((x:any)=>x[key]));for(const key of Object.keys(all[0].events))if(all.some((x:any)=>x.events[key]!==all[0].events[key]))throw Error("monitor load cgroup event changed");for(const segment of [[...phases.slice(0,6).flatMap((p:any)=>p.snapshots),phases[6].snapshots[0]],[phases[6].snapshots[1],...phases.slice(7).flatMap((p:any)=>p.snapshots)]])assertSeries(segment.map((x:any)=>x.hwm));
 const phaseAt=(i:number)=>phases[i], laneAt=(i:number)=>r.lanes[i], lanePhase=[0,3],drainPhase=[1,4],quietPhase=[2,5];for(let i=0;i<2;i++){const l=laneAt(i),p=phaseAt(lanePhase[i]),d=phaseAt(drainPhase[i]),q=phaseAt(quietPhase[i]);if(!exact(l,["completed","drainDurationMs","durationMs","failures","latenciesMs","maxima","offered","p95Ms","p99Ms","quietDurationMs","snapshots","warmupCount"])||l.durationMs!==p.workDurationMs||l.drainDurationMs!==d.workDurationMs||l.quietDurationMs!==q.workDurationMs||l.durationMs<60000||l.drainDurationMs<5000||l.quietDurationMs<30000||l.warmupCount!==128||!int(l.offered)||l.offered<3200||l.completed!==l.offered||l.failures!==0||!Array.isArray(l.latenciesMs)||l.latenciesMs.length!==l.offered||l.latenciesMs.some((x:any)=>!int(x))||l.p95Ms!==rank(l.latenciesMs,.95)||l.p99Ms!==rank(l.latenciesMs,.99)||l.p95Ms>500||l.p99Ms>1000||JSON.stringify(l.snapshots)!==JSON.stringify(p.snapshots)||!sameRecord(l.maxima,maxima(p.snapshots)))throw Error("monitor load lane differs");}
 const rec=r.recovery,p=phaseAt(7);if(!exact(rec,["completed","durationMs","failures","latenciesMs","offered","p95Ms","p99Ms","warmupCount"])||rec.durationMs!==p.workDurationMs||rec.durationMs<10000||rec.warmupCount!==128||!int(rec.offered)||rec.completed!==rec.offered||rec.completed<512||rec.failures!==0||!Array.isArray(rec.latenciesMs)||rec.latenciesMs.length!==rec.offered||rec.latenciesMs.some((x:any)=>!int(x))||rec.p95Ms!==rank(rec.latenciesMs,.95)||rec.p99Ms!==rank(rec.latenciesMs,.99)||rec.p95Ms>500||rec.p99Ms>1000||r.faultDurationMs!==phaseAt(6).workDurationMs)throw Error("monitor load recovery differs");
 const fp=phaseAt(6),expected=["stop","listenerGone","listenerReady","registryHealthy"];if(!Array.isArray(r.fault)||r.fault.length!==4||JSON.stringify(r.fault.map((x:any)=>x.step))!==JSON.stringify(expected)||r.fault.some((x:any,i:number)=>!obj(x)||!int(x.at)||(i&&x.at<=r.fault[i-1].at))||!exact(r.fault[0],["at","step"])||!exact(r.fault[1],["at","code","status","step"])||r.fault[1].status!==503||r.fault[1].code!==40001||!exact(r.fault[2],["at","pid","sha256","step"])||r.fault[2].pid!==fp.services.after.monitor.pid||r.fault[2].sha256!==fp.services.after.monitor.sha256||!exact(r.fault[3],["at","step"])||!(fp.snapshots[0].at<r.fault[0].at&&r.fault[3].at<fp.snapshots[1].at))throw Error("monitor load fault milestones differ");
 if(!Array.isArray(r.boundary)||r.boundary.length<4||r.boundary.some((x:any,i:number)=>!exact(x,["at","code","kind","status"])||!int(x.at)||x.kind!=="response"||x.status!==503||x.code!==40001||x.at<r.fault[0].at||x.at>r.fault[1].at||(i&&x.at<r.boundary[i-1].at))||r.boundary.at(-1).at-r.boundary[0].at<750||r.boundary.at(-1).at!==r.fault[1].at||r.boundary.at(-1).at>r.fault[2].at)throw Error("monitor load stable outage differs");
 if(r.boundaryInFlight.some((x:any)=>x.start<fp.snapshots[0].at||x.end>r.fault[1].at))throw Error("monitor load inflight window differs");
 const q=[phaseAt(2).snapshots[1],phaseAt(5).snapshots[1]];if(!Array.isArray(r.quietBaselines)||r.quietBaselines.length!==2||r.quietBaselines.some((x:any,i:number)=>!exact(x,["at","pidsCurrent","rss"])||x.at!==q[i].at||x.rss!==q[i].rss||x.pidsCurrent!==q[i].pidsCurrent||x.rss>q[0].rss+16*1024*1024||x.pidsCurrent>q[0].pidsCurrent+2))throw Error("monitor load quiet differs");
 if(!exact(r.overallMaxima,["hwm","memoryCurrent","memoryPeak","pidsPeak","rss"])||r.overallMaxima.memoryPeak>384*1024*1024||r.overallMaxima.pidsPeak>64||r.overallMaxima.rss>384*1024*1024||r.overallMaxima.hwm>384*1024*1024||!sameRecord(r.overallMaxima,maxima(all))||!reading(r.resources)||!sameRecord(r.resources,all[0])||!exact(r.pureMonitorSse,["runtimeStatus","signedAbsence"])||r.pureMonitorSse.runtimeStatus!==404)throw Error("monitor load resources differs");return r;
}
