#!/usr/bin/env bash

create_system() { curl_json "${owner_auth[@]}" -H 'content-type: application/json' -d "$(jq -nc --arg name "$1" '{name:$name,baseUrl:"http://127.0.0.1:19801/health",enabled:true}')" "$admin/api/reports/systems" | jq -er '.data.id'; }
create_flow() { curl_json "${owner_auth[@]}" -H 'content-type: application/json' -d "$(jq -nc --arg system "$system_id" --arg name "$1" --argjson steps "$2" '{systemId:$system,name:$name,steps:$steps}')" "$admin/api/reports/flows" | jq -er '.data.id'; }
create_run() { curl_json "${owner_auth[@]}" -H 'content-type: application/json' -d "$(jq -nc --arg flow "$1" '{flowId:$flow,input:{}}')" "$admin/api/reports/runs" | jq -er '.data.id'; }
wait_for_status() { local run_id=$1 expected=$2 status; for _ in $(seq 1 600); do status=$(curl_json "${owner_auth[@]}" "$admin/api/reports/runs/$run_id" | jq -er '.data.status') || return 1; [ "$status" = "$expected" ] && return 0; case "$status" in failed|cancelled) return 1;; esac; sleep .1; done; return 1; }
run_browser_case() { local flow run; flow=$(create_flow "Reports UI state $1" "$2") || return 1; run=$(create_run "$flow") || return 1; wait_for_status "$run" succeeded || return 1; printf '%s\n' "$run"; }
download_screenshot() { local artifact_id hash dimensions root=${reports_ui_state_evidence_dir:-/verify/evidence}; artifact_id=$(curl_json "${owner_auth[@]}" "$admin/api/reports/runs/$1/artifacts" | jq -er --arg prefix "$2" '.data[] | select(.fileName | startswith($prefix)) | .id') || return 1; curl_json "${owner_auth[@]}" "$admin/api/reports/runs/$1/artifacts/$artifact_id" >"$root/$3" || return 1; hash=$(sha256sum "$root/$3" | awk '{print $1}') || return 1; dimensions=$(file "$root/$3" | sed -E 's/.*PNG image data, ([0-9]+ x [0-9]+).*/\1/') || return 1; test "$dimensions" = "$5 x $6" || return 1; jq -nc --arg case "$4" --arg file "$3" --arg sha "$hash" --arg dimensions "$dimensions" --argjson width "$5" --argjson height "$6" '{case:$case,file:$file,sha256:$sha,dimensions:$dimensions,viewport:{width:$width,height:$height}}' || return 1; }
evidence_file_descriptor() { local root=${reports_ui_state_evidence_dir:-/verify/evidence}; jq -nc --arg file "$1" --arg sha "$(sha256sum "$root/$1" | awk '{print $1}')" '{file:$file,sha256:$sha}'; }
save_run_steps() { local receipt="run-steps/$2" root=${reports_ui_state_evidence_dir:-/verify/evidence}; mkdir -p "$root/run-steps" || return 1; curl_json "${owner_auth[@]}" "$admin/api/reports/runs/$1/steps" >"$root/$receipt" || return 1; jq -e --arg run "$1" '(.data|type == "array" and length>0) and all(.data[];.runId==$run)' "$root/$receipt" >/dev/null || return 1; jq -nc --arg run "$1" --arg file "$receipt" --arg sha "$(sha256sum "$root/$receipt" | awk '{print $1}')" '{runId:$run,file:$file,sha256:$sha}' || return 1; }
