#!/usr/bin/env bash
set -euo pipefail

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
docker_bin=${RUSTZEN_TASK_CONSOLE_DOCKER:-docker}
source_identity=${RUSTZEN_TASK_CONSOLE_SOURCE_IDENTITY:-"$root/scripts/admin-browser-source-identity.sh"}
verifier_helper=${RUSTZEN_TASK_CONSOLE_VERIFIER_HELPER:-"$root/scripts/ensure-admin-browser-verifier-image.sh"}
timeout=${RUSTZEN_TASK_CONSOLE_TIMEOUT:-600}
cleanup_timeout=${RUSTZEN_TASK_CONSOLE_CLEANUP_TIMEOUT:-10}
info_timeout=${RUSTZEN_TASK_CONSOLE_DOCKER_INFO_TIMEOUT:-10}
evidence_root=${RUSTZEN_TASK_CONSOLE_EVIDENCE_ROOT:-"$root/target/rz/task-console"}
current="$evidence_root/current"; command_pid=; watchdog_pid=; container_active=0; published=0

validate_seconds() { case "$1" in ''|*[!0-9]*) echo "$2 must be a positive integer" >&2; exit 2;; esac; [ "$1" -gt 0 ] && [ "$1" -le "$3" ] || { echo "$2 must be 1..$3 seconds" >&2; exit 2; }; }
run_bounded() { local seconds=$1 marker status; shift; marker=$(mktemp "${TMPDIR:-/tmp}/rz-task-console-timeout.XXXXXX"); rm -f "$marker"; "$@" & command_pid=$!; ( sleep "$seconds"; : >"$marker"; kill -TERM "$command_pid" 2>/dev/null || true; sleep 2; kill -KILL "$command_pid" 2>/dev/null || true ) >/dev/null 2>&1 & watchdog_pid=$!; if wait "$command_pid"; then status=0; else status=$?; fi; kill -TERM "$watchdog_pid" 2>/dev/null || true; wait "$watchdog_pid" 2>/dev/null || true; command_pid=; watchdog_pid=; [ ! -e "$marker" ] || status=124; rm -f "$marker"; return "$status"; }
run_capture() { local output status; output=$(mktemp "${TMPDIR:-/tmp}/rz-task-console-capture.XXXXXX"); if run_bounded "$@" >"$output"; then status=0; else status=$?; fi; cat "$output"; rm -f "$output"; return "$status"; }
atomic_replace_symlink() { case "$(uname -s)" in Darwin|FreeBSD) mv -fh "$1" "$2";; *) mv -Tf "$1" "$2";; esac; }
sha() { shasum -a 256 "$1" | awk '{print $1}'; }
provenance_hash() { awk -F '\t' -v name="$2" '$1 == name { print $2; exit }' "$1"; }
verify_build_provenance() { awk -F '\t' -v head="$head" -v state="$tree_state" -v digest="$tree_sha" -v arch="$architecture" -v target="$target_triple" -v platform="$platform" '
  $1=="schemaVersion"&&$2=="1"{a=1} $1=="gitHead"&&$2==head{b=1} $1=="sourceTreeState"&&$2==state{c=1} $1=="sourceTreeSha256"&&$2==digest{d=1} $1=="architecture"&&$2==arch{e=1} $1=="targetTriple"&&$2==target{f=1} $1=="platform"&&$2==platform{g=1} $1=="distribution"&&$2=="full"{h=1} END{exit !(a&&b&&c&&d&&e&&f&&g&&h)}' "$1"; }
stage_binary() { local name=$1 expected actual; cp "$bin_dir/$name" "$staged/$name"; expected=$(provenance_hash "$candidate/build-provenance.txt" "$name"); actual=$(sha "$staged/$name"); [ -n "$expected" ] && [ "$actual" = "$expected" ]; }
verify_staged_binaries() { local name expected actual; for name in rz-admin rz-monitor rz-insights rz-reports; do expected=$(provenance_hash "$candidate/build-provenance.txt" "$name"); actual=$(sha "$staged/$name"); [ -n "$expected" ] && [ "$actual" = "$expected" ] || return 1; done; }
verify_evidence() { local manifest=$1 receipt file expected actual size dimensions; jq -e --arg head "$head" --arg state "$tree_state" --arg source "$tree_sha" --arg platform "$platform" --arg provenance "$build_provenance_sha" --argjson binaries "$expected_binaries" --argjson receiptFiles "$expected_receipts" '
  .schemaVersion == 2 and .status == "passed" and .gitHead == $head and .sourceTreeState == $state and .sourceTreeSha256 == $source and .platform == $platform and .buildProvenanceSha256 == $provenance and ([.binaries[] | {name,sha256}] | sort_by(.name)) == ($binaries | sort_by(.name)) and ([.receipts[].file] | sort) == ($receiptFiles | sort) and (.screenshots | type == "array" and length == 2) and ([.screenshots[].file] | sort) == ["task-console-desktop.png","task-console-mobile.png"] and (.screenshots[] | .sha256 | type == "string" and test("^[0-9a-f]{64}$")) and .api.taskCount == 3 and .api.listOnlyPost == 403 and (.api.manualRun.id | type == "string" and length > 0) and .api.manualRun.status == "success" and (.browser | (.ownerRun,.recordRun,.viewerRun,.emptyRun,.errorRun | type == "string" and length > 0))' "$manifest" >/dev/null || return 1
  while IFS=$'\t' read -r file expected size; do case "$file" in ''|*/*|*..*) return 1;; esac; [ -f "$candidate/$file" ] && [ ! -L "$candidate/$file" ] && [ "$(sha "$candidate/$file")" = "$expected" ] && [ "$(wc -c < "$candidate/$file")" = "$size" ] || return 1; done < <(jq -r '.receipts[] | [.file,.sha256,.bytes] | @tsv' "$manifest")
  while IFS=$'\t' read -r file expected dimensions width height; do case "$file" in task-console-desktop.png|task-console-mobile.png);; *) return 1;; esac; [ -f "$candidate/$file" ] && [ ! -L "$candidate/$file" ] || return 1; [ "$(head -c 8 "$candidate/$file" | od -An -tx1 | tr -d ' \n')" = 89504e470d0a1a0a ] && [ "$(sha "$candidate/$file")" = "$expected" ] || return 1; actual=$(file "$candidate/$file" | sed -E 's/.*PNG image data, ([0-9]+ x [0-9]+).*/\1/'); [ "$actual" = "$dimensions" ] && [ "$dimensions" = "$width x $height" ] || return 1; done < <(jq -r '.screenshots[] | [.file,.sha256,.dimensions,.viewport.width,.viewport.height] | @tsv' "$manifest")
  jq -e --slurpfile before "$candidate/list-only-runs-before.json" --slurpfile after "$candidate/list-only-runs-after.json" --slurpfile transition "$candidate/task-transition-receipt.json" --slurpfile empty "$candidate/empty-receipt.json" --slurpfile response "$candidate/empty-response.json" --slurpfile owner "$candidate/browser-owner-run.json" --slurpfile record "$candidate/browser-owner-record-run.json" '.api.manualRun.id as $manual | ($before[0].total == $after[0].total) and ([$before[0].data[] | {id,status}] == [$after[0].data[] | {id,status}]) and (($transition[0].transitionRunId | tostring) == $manual) and $empty[0] == {method:"GET",mode:"empty",route:"/api/manage/tasks",hitCount:$empty[0].hitCount} and ($empty[0].hitCount >= 1) and $response[0] == {code:0,message:"Success",data:[],total:0} and $owner[0].data.status == "succeeded" and $record[0].data.status == "succeeded" and $manual != ""' "$manifest" >/dev/null
}
remove_container() { local listing; run_bounded "$cleanup_timeout" "$docker_bin" rm -f "$container" >/dev/null 2>&1 || { echo "failed to remove Docker container $container" >&2; return 1; }; listing=$(run_capture "$cleanup_timeout" "$docker_bin" ps -a --filter "name=^/${container}$" --format '{{.Names}}') || { echo "Docker absence check failed for $container" >&2; return 1; }; [ -z "$listing" ] || { echo "Docker container still exists after removal: $container" >&2; return 1; }; }
capture_log() { run_bounded "$cleanup_timeout" "$docker_bin" logs "$container" >"$candidate/container.log" 2>&1 || true; [ -s "$candidate/container.log" ] || printf 'no Docker log was available for %s\n' "$container" >"$candidate/container.log"; }
current_is_published() { [ -L "$current" ] && [ "$(readlink "$current")" = "runs/$run_id" ]; }
preserve_failure() { local result=$1 cleanup_status=$2 source= file; if [ -d "$candidate" ]; then source=$candidate; elif [ "$published" = 0 ] && [ -d "$published_run" ]; then source=$published_run; else return 0; fi; mkdir -p "$failed"; printf 'exitStatus\t%s\ncleanupStatus\t%s\ncontainer\t%s\n' "$result" "$cleanup_status" "$container" >"$failed/failure-summary.tsv"; for file in container.log build-provenance.txt; do [ ! -f "$source/$file" ] || cp "$source/$file" "$failed/$file"; done; rm -rf "$source"; }
publish_candidate() { [ "${RUSTZEN_TASK_CONSOLE_TEST_PUBLISH_FAILURE:-}" != before-move ] || return 1; mv "$candidate" "$published_run" && [ "${RUSTZEN_TASK_CONSOLE_TEST_PUBLISH_FAILURE:-}" != after-move ] && ln -s "runs/$run_id" "$publish_link" && [ "${RUSTZEN_TASK_CONSOLE_TEST_PUBLISH_FAILURE:-}" != after-link ] && atomic_replace_symlink "$publish_link" "$current" && published=1; }
cleanup() { local result=$? cleanup_status=0; trap - EXIT INT TERM; if [ "$container_active" = 1 ] && [ -d "$candidate" ]; then capture_log; remove_container || cleanup_status=125; fi; if [ "$result" -ne 0 ] || [ "$cleanup_status" -ne 0 ]; then preserve_failure "$result" "$cleanup_status"; fi; rm -rf "$candidate" "$staged" "$publish_link"; if [ "$cleanup_status" -eq 0 ]; then rm -rf "$lock_dir"; else echo "cleanup failed; ownership lock retained at $lock_dir" >&2; result=125; fi; exit "$result"; }

validate_seconds "$timeout" RUSTZEN_TASK_CONSOLE_TIMEOUT 900; validate_seconds "$cleanup_timeout" RUSTZEN_TASK_CONSOLE_CLEANUP_TIMEOUT 60; validate_seconds "$info_timeout" RUSTZEN_TASK_CONSOLE_DOCKER_INFO_TIMEOUT 60
architecture=${RUSTZEN_UI_LINUX_ARCH:-}; if [ -z "$architecture" ]; then architecture=$(run_capture "$info_timeout" "$docker_bin" info --format '{{.Architecture}}') || { echo 'Docker architecture discovery failed or timed out' >&2; exit 1; }; fi
case "$architecture" in x86_64) platform=linux/amd64; target_triple=x86_64-unknown-linux-musl;; aarch64) platform=linux/arm64; target_triple=aarch64-unknown-linux-musl;; *) echo "unsupported Docker architecture: $architecture" >&2; exit 2;; esac
read -r head tree_state tree_sha < <("$source_identity")
bin_dir=${RUSTZEN_UI_LINUX_BIN_DIR:-"$root/target/rz/build/$architecture/bin"}
run_id="$(date -u +%Y%m%dT%H%M%SZ)-$$"; lock_dir="$evidence_root/.verify.lock"; candidate="$evidence_root/.candidate-$run_id"; staged="$evidence_root/.binaries-$run_id"; published_run="$evidence_root/runs/$run_id"; publish_link="$evidence_root/.current-$run_id"; failed="$evidence_root/failed-runs/$run_id"; container="rz-task-console-$run_id"
mkdir -p "$evidence_root/runs" "$evidence_root/failed-runs"; [ ! -e "$current" ] || [ -L "$current" ] || { echo 'refusing non-symlink task-console current evidence path' >&2; exit 1; }; mkdir "$lock_dir" 2>/dev/null || { echo 'task console verifier already running' >&2; exit 1; }; mkdir "$candidate" "$staged"; trap cleanup EXIT; trap 'exit 130' INT; trap 'exit 143' TERM
test -s "$bin_dir/build-provenance.txt" || { echo 'missing build provenance' >&2; exit 1; }; cp "$bin_dir/build-provenance.txt" "$candidate/build-provenance.txt"; verify_build_provenance "$candidate/build-provenance.txt" || { echo 'Linux provenance does not match current source identity' >&2; exit 1; }
for name in rz-admin rz-monitor rz-insights rz-reports; do test -x "$bin_dir/$name" || { echo "missing Linux binary: $bin_dir/$name; run just build-admin-browser-linux" >&2; exit 1; }; stage_binary "$name" || { echo "staged Linux binary differs from immutable provenance: $name" >&2; exit 1; }; done
verify_staged_binaries || { echo 'staged Linux binaries changed after staging' >&2; exit 1; }
expected_binaries=$(for name in rz-admin rz-monitor rz-insights rz-reports; do jq -nc --arg name "$name" --arg sha "$(sha "$staged/$name")" '{name:$name,sha256:$sha}'; done | jq -s .); expected_receipts=$(printf '%s\n' tasks.json list-only-tasks.json list-only-runs-before.json list-only-post.json list-only-status.txt list-only-runs-after.json owner-runs-after.json task-transition-receipt.json empty-receipt.json empty-response.json error-receipt.json browser-owner-run.json browser-owner-steps.json browser-owner-artifacts.json browser-owner-record-run.json browser-owner-record-steps.json browser-owner-record-artifacts.json browser-viewer-run.json browser-viewer-steps.json browser-viewer-artifacts.json browser-empty-run.json browser-empty-steps.json browser-empty-artifacts.json browser-error-run.json browser-error-steps.json browser-error-artifacts.json | jq -R . | jq -s .); build_provenance_sha=$(sha "$candidate/build-provenance.txt")
if [ "${RUSTZEN_TASK_CONSOLE_TEST_REPLACE_STAGED:-}" = 1 ]; then printf replacement >"$staged/rz-monitor"; fi
verify_staged_binaries || { echo 'staged Linux binaries changed after staging' >&2; exit 1; }
if [ "${RUSTZEN_TASK_CONSOLE_TEST_STOP_AFTER_STAGING:-}" = 1 ]; then exit 0; fi
if [ "${RUSTZEN_TASK_CONSOLE_TEST_SOURCE_CHANGED:-}" = 1 ]; then read -r final_head final_state final_sha < <("$source_identity"); [ "$final_head:$final_state:$final_sha" = "$head:$tree_state:$tree_sha" ] || { echo 'source tree changed during task console verification' >&2; exit 1; }; echo 'source-change seam unexpectedly matched' >&2; exit 99; fi
if [ -n "${RUSTZEN_TASK_CONSOLE_TEST_PUBLISH_FAILURE:-}" ]; then mkdir -p "$evidence_root/runs/old"; printf old >"$evidence_root/runs/old/manifest.json"; [ -e "$current" ] || ln -s runs/old "$current"; printf new >"$candidate/manifest.json"; if publish_candidate; then echo 'forced task-console publication failure unexpectedly succeeded' >&2; exit 1; fi; [ "$(readlink "$current")" = runs/old ] || { echo 'failed publication changed current' >&2; exit 1; }; exit 1; fi
if [ "${RUSTZEN_TASK_CONSOLE_TEST_CLEANUP:-}" = 1 ]; then mkdir -p "$evidence_root/runs/old"; printf old >"$evidence_root/runs/old/manifest.json"; [ -e "$current" ] || ln -s runs/old "$current"; container_active=1; exit 1; fi
read -r image _ _ < <("$verifier_helper" --platform "$platform")
container_active=1
run_bounded "$timeout" "$docker_bin" run --name "$container" --platform "$platform" --security-opt seccomp=unconfined --env RUSTZEN_VERIFY_HEAD="$head" --env RUSTZEN_VERIFY_SOURCE_TREE_STATE="$tree_state" --env RUSTZEN_VERIFY_SOURCE_TREE_SHA256="$tree_sha" --env RUSTZEN_VERIFY_ARCHITECTURE="$architecture" --env RUSTZEN_VERIFY_PLATFORM="$platform" --env RUSTZEN_VERIFY_BUILD_PROVENANCE_SHA256="$build_provenance_sha" --env RUSTZEN_VERIFY_BINARY_HASHES="$(for name in rz-admin rz-monitor rz-insights rz-reports; do jq -nc --arg name "$name" --arg sha "$(sha "$staged/$name")" '{($name):$sha}'; done | jq -s add)" --mount "type=bind,src=$staged,dst=/verify/bin,readonly" --mount "type=bind,src=$candidate,dst=/verify/evidence" --mount "type=bind,src=$root/scripts/verify-task-console-linux-inner.sh,dst=/verify/run.sh,readonly" --mount "type=bind,src=$root/scripts/admin-browser-fault-proxy.py,dst=/verify/fault-proxy.py,readonly" "$image" bash /verify/run.sh
remove_container; container_active=0
verify_evidence "$candidate/manifest.json" || { echo 'task-console evidence did not match its bound manifest' >&2; exit 1; }
verify_staged_binaries || { echo 'staged Linux binaries changed during verification' >&2; exit 1; }
read -r final_head final_state final_sha < <("$source_identity"); [ "$final_head:$final_state:$final_sha" = "$head:$tree_state:$tree_sha" ] || { echo 'source tree changed during task console verification' >&2; exit 1; }
publish_candidate; rm -rf "$staged" "$lock_dir"; trap - EXIT INT TERM; echo "Task console Linux evidence published: $current/manifest.json"
