#!/usr/bin/env bash
set -euo pipefail
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
docker_bin=${RUSTZEN_ANALYTICS_UI_STATE_DOCKER:-docker}
timeout=${RUSTZEN_ANALYTICS_UI_STATE_TIMEOUT:-480}
info_timeout=${RUSTZEN_ANALYTICS_UI_STATE_DOCKER_INFO_TIMEOUT:-10}
bounded_child_pid=; bounded_watchdog_pid=; published_committed=0
validate_timeout() { local value=$1 name=$2 maximum=$3; case "$value" in ''|*[!0-9]*) echo "$name must be a positive integer" >&2; exit 2;; esac; [ "$value" -gt 0 ] && [ "$value" -le "$maximum" ] || { echo "$name must be 1..$maximum seconds" >&2; exit 2; }; }
pid_alive() { local state; kill -0 "$1" 2>/dev/null || return 1; state=$(ps -o stat= -p "$1" 2>/dev/null | tr -d ' '); case "$state" in Z*) return 1;; *) return 0;; esac; }
collect_process_tree() { local pid=$1 child; printf '%s\n' "$pid"; for child in $(pgrep -P "$pid" 2>/dev/null || true); do collect_process_tree "$child"; done; }
stop_frozen_processes() { local targets_file=$1 attempt target any_alive; while read -r target; do kill -TERM "$target" 2>/dev/null || true; done <"$targets_file"; for attempt in $(seq 1 5); do any_alive=0; while read -r target; do if pid_alive "$target"; then any_alive=1; break; fi; done <"$targets_file"; [ "$any_alive" = 0 ] && break; sleep .05; done; while read -r target; do pid_alive "$target" && kill -KILL "$target" 2>/dev/null || true; done <"$targets_file"; }
stop_process_tree() { local pid=${1:-} targets_file; [ -n "$pid" ] || return 0; targets_file=$(mktemp "${TMPDIR:-/tmp}/rz-analytics-ui-state-targets.XXXXXX") || return 1; collect_process_tree "$pid" >"$targets_file"; stop_frozen_processes "$targets_file"; rm -f "$targets_file"; wait "$pid" 2>/dev/null || true; }
cleanup_bounded_processes() { stop_process_tree "$bounded_child_pid"; stop_process_tree "$bounded_watchdog_pid"; bounded_child_pid=; bounded_watchdog_pid=; }
run_bounded() { local seconds=$1 status timeout_state timeout_done timeout_fired timeout_targets; shift; timeout_state=${RUSTZEN_ANALYTICS_UI_STATE_TIMEOUT_STATE_DIR:-$(mktemp -d "${TMPDIR:-/tmp}/rz-analytics-ui-state-timeout.XXXXXX")}; mkdir -p "$timeout_state"; timeout_done="$timeout_state/done"; timeout_fired="$timeout_state/fired"; timeout_targets="$timeout_state/targets"; "$@" & bounded_child_pid=$!; ( [ -n "${RUSTZEN_ANALYTICS_UI_STATE_TEST_TIMEOUT_WATCHDOG_RECEIPT:-}" ] && printf '%s\n' "$BASHPID" >"$RUSTZEN_ANALYTICS_UI_STATE_TEST_TIMEOUT_WATCHDOG_RECEIPT"; sleep "$seconds"; [ -e "$timeout_done" ] && exit 0; : >"$timeout_fired"; collect_process_tree "$bounded_child_pid" >"$timeout_targets"; stop_frozen_processes "$timeout_targets" ) >/dev/null 2>&1 & bounded_watchdog_pid=$!; if wait "$bounded_child_pid"; then status=0; else status=$?; fi; if [ -e "$timeout_fired" ]; then wait "$bounded_watchdog_pid" 2>/dev/null || true; bounded_watchdog_pid=; bounded_child_pid=; rm -rf "$timeout_state"; return 124; fi; : >"$timeout_done"; stop_process_tree "$bounded_watchdog_pid"; bounded_watchdog_pid=; bounded_child_pid=; rm -rf "$timeout_state"; return "$status"; }
run_bounded_capture() { local capture status; capture=$(mktemp "${TMPDIR:-/tmp}/rz-analytics-ui-state.XXXXXX") || return 1; if run_bounded "$@" >"$capture"; then status=0; else status=$?; fi; cat "$capture"; rm -f "$capture"; return "$status"; }
atomic_replace_symlink() { case "$(uname -s)" in Darwin|FreeBSD) mv -fh "$1" "$2";; *) mv -Tf "$1" "$2";; esac; }
provenance_hash() { awk -F '\t' -v name="$2" '$1 == name { print $2; exit }' "$1"; }
stage_binary() { local name=$1 expected actual; cp "$bin_dir/$name" "$staged/$name"; file "$staged/$name" | grep -q "$file_pattern"; expected=$(provenance_hash "$candidate/build-provenance.txt" "$name"); actual=$(shasum -a 256 "$staged/$name" | awk '{print $1}'); [ -n "$expected" ] && test "$actual" = "$expected"; }
verify_artifacts() { local manifest=$1 desktop mobile; desktop=$(shasum -a 256 "$candidate/analytics-overview-desktop-dark-en.png" | awk '{print $1}'); mobile=$(shasum -a 256 "$candidate/analytics-details-mobile-light-zh.png" | awk '{print $1}'); jq -e --arg desktop "$desktop" --arg mobile "$mobile" '([.artifacts[] | select(.file == "analytics-overview-desktop-dark-en.png" and .sha256 == $desktop and .dimensions == "1440 x 900")] | length) == 1 and ([.artifacts[] | select(.file == "analytics-details-mobile-light-zh.png" and .sha256 == $mobile and .dimensions == "390 x 844")] | length) == 1' "$manifest" >/dev/null; }
verify_step_receipts() { jq -e --slurpfile expected "$2" '. as $manifest | [$expected[0] | to_entries[] | .key as $name | .value as $expectedSteps | ($manifest.runSteps[$name] | type == "array" and length == ($expectedSteps | length) and ([range(0; $expectedSteps | length) | . as $i | $manifest.runSteps[$name][$i].action == $expectedSteps[$i].action and $manifest.runSteps[$name][$i].status == "succeeded"] | all))] | all' "$1" >/dev/null; }
verify_manifest() { local manifest=$1 expected=$2 head=$3 state=$4 sha=$5 platform=$6; jq -e --arg head "$head" --arg state "$state" --arg sha "$sha" --arg platform "$platform" '. as $manifest | .schemaVersion == 1 and .status == "passed" and .gitHead == $head and .sourceTreeState == $state and .sourceTreeSha256 == $sha and .platform == $platform and (["overviewLoading","detailsEmpty","overview403","details403","overview500","details500","detailsFilterResetsPage","detailsBackgroundRefresh","overviewBackground403","detailsBackground403"] | map(. as $name | ($manifest.runs[$name] | type == "string" and length > 0)) | all)' "$manifest" >/dev/null; verify_step_receipts "$manifest" "$expected"; }
current_is_published() { [ -L "$current" ] && [ "$(readlink "$current")" = "runs/$run_id" ]; }
move_failure_evidence() { local source=; if current_is_published || [ "$published_committed" = 1 ]; then return 0; fi; if [ -d "${published_run:-}" ]; then source=$published_run; elif [ -d "${candidate:-}" ]; then source=$candidate; fi; [ -n "$source" ] || return 0; failed_dir="$evidence_root/failed-runs/$run_id"; mkdir -p "$evidence_root/failed-runs"; rm -rf "$failed_dir"; mv "$source" "$failed_dir"; }
publish_candidate() { [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_PUBLISH_FAILURE:-}" != before-move ] || return 1; mv "$candidate" "$published_run" || return 1; [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_PUBLISH_FAILURE:-}" != after-move ] || return 1; ln -s "runs/$run_id" "$publish_link" || return 1; [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_PUBLISH_FAILURE:-}" != after-link ] || return 1; [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_PUBLISH_FAILURE:-}" != replace ] || return 1; atomic_replace_symlink "$publish_link" "$current"; published_committed=1; [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_PUBLISH_FAILURE:-}" != after-replace ] || return 1; }

if [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_TIMEOUT:-}" = 1 ]; then
  test_root=${RUSTZEN_ANALYTICS_UI_STATE_TEST_ROOT:-$(mktemp -d "${TMPDIR:-/tmp}/rz-analytics-ui-state-timeout-seam.XXXXXX")}; mkdir -p "$test_root"; timeout_state="$test_root/timeout-state"; watchdog_receipt="$test_root/watchdog.pid"
  if RUSTZEN_ANALYTICS_UI_STATE_TIMEOUT_STATE_DIR="$timeout_state" RUSTZEN_ANALYTICS_UI_STATE_TEST_TIMEOUT_WATCHDOG_RECEIPT="$watchdog_receipt" run_bounded 1 sh -c 'trap "exit 0" TERM; sh -c '"'"'trap "" TERM; while :; do sleep 60; done'"'"' & echo $! > "$1"; wait' sh "$test_root/grandchild.pid" >"$test_root/output" 2>&1; then echo 'timeout seam unexpectedly succeeded' >&2; exit 1; else timeout_status=$?; fi
  timeout_grandchild=$(cat "$test_root/grandchild.pid")
  timeout_watchdog=$(cat "$watchdog_receipt"); test "$timeout_status" = 124 && ! pid_alive "$timeout_grandchild" && ! pid_alive "$timeout_watchdog" && ! test -e "$timeout_state" || exit 99
  rm -rf "$test_root"; echo 'Analytics UI state timeout tree seam passed'; exit 0
fi

if [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_SIGNAL:-}" = INT ] || [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_SIGNAL:-}" = TERM ]; then
  test_root=${RUSTZEN_ANALYTICS_UI_STATE_TEST_ROOT:-$(mktemp -d "${TMPDIR:-/tmp}/rz-analytics-ui-state-signal.XXXXXX")}; signal=$RUSTZEN_ANALYTICS_UI_STATE_TEST_SIGNAL; evidence_root=$test_root; current="$test_root/current"; lock_dir="$test_root/.verify.lock"; candidate="$test_root/.candidate"; staged="$test_root/.staged"
  mkdir -p "$test_root/runs/old" "$candidate" "$staged" "$lock_dir"; printf old >"$test_root/runs/old/manifest.json"; ln -s runs/old "$current"; sh -c 'trap "exit 0" TERM; sh -c '"'"'trap "" TERM; while :; do sleep 60; done'"'"' & echo $! > "$1"; wait' sh "$test_root/grandchild.pid" & bounded_child_pid=$!; for _ in $(seq 1 20); do [ -s "$test_root/grandchild.pid" ] && break; sleep .01; done; grandchild=$(cat "$test_root/grandchild.pid"); sh -c 'trap '"'"'sleep .1; printf graceful > "$1"; exit 0'"'"' TERM; while :; do sleep 60; done' sh "$test_root/graceful.receipt" & bounded_watchdog_pid=$!; child=$bounded_child_pid; watchdog=$bounded_watchdog_pid
  cleanup_signal() { result=$?; trap - EXIT INT TERM; cleanup_bounded_processes; rm -rf "$candidate" "$staged" "$lock_dir"; expected=130; [ "$signal" = TERM ] && expected=143; test "$result" = "$expected" && ! pid_alive "$child" && ! pid_alive "$grandchild" && ! pid_alive "$watchdog" && test "$(cat "$test_root/graceful.receipt")" = graceful && test "$(readlink "$current")" = runs/old && ! test -e "$candidate" && ! test -e "$staged" && ! test -e "$lock_dir" || exit 99; echo "Analytics UI state $signal signal seam passed" >&2; exit "$result"; }
  trap cleanup_signal EXIT; trap 'exit 130' INT; trap 'exit 143' TERM; kill -"$signal" "$$"
fi
if [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_AFTER_REPLACE_SIGNAL:-}" = INT ] || [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_AFTER_REPLACE_SIGNAL:-}" = TERM ]; then
  test_root=${RUSTZEN_ANALYTICS_UI_STATE_TEST_ROOT:-$(mktemp -d "${TMPDIR:-/tmp}/rz-analytics-ui-state-commit.XXXXXX")}; signal=$RUSTZEN_ANALYTICS_UI_STATE_TEST_AFTER_REPLACE_SIGNAL; evidence_root=$test_root; current="$test_root/current"; lock_dir="$test_root/.verify.lock"; run_id=test; candidate="$test_root/.candidate"; staged="$test_root/.staged"; published_run="$test_root/runs/$run_id"; publish_link="$test_root/.current-$run_id"
  mkdir -p "$test_root/runs/old" "$candidate" "$staged" "$lock_dir"; printf old >"$test_root/runs/old/manifest.json"; printf new >"$candidate/manifest.json"; ln -s runs/old "$current"
  cleanup_commit() { result=$?; trap - EXIT INT TERM; rm -rf "$staged" "$publish_link" "$lock_dir"; move_failure_evidence; expected=130; [ "$signal" = TERM ] && expected=143; test "$result" = "$expected" && current_is_published && test "$(cat "$current/manifest.json")" = new && ! test -e "$publish_link" && ! test -e "$lock_dir" || exit 99; echo "Analytics UI state $signal after-replace signal seam passed" >&2; exit "$result"; }
  trap cleanup_commit EXIT; trap 'exit 130' INT; trap 'exit 143' TERM; publish_candidate; kill -"$signal" "$$"
fi
if [ -n "${RUSTZEN_ANALYTICS_UI_STATE_TEST_PUBLISH_FAILURE:-}" ]; then
  test_root=${RUSTZEN_ANALYTICS_UI_STATE_TEST_ROOT:-$(mktemp -d "${TMPDIR:-/tmp}/rz-analytics-ui-state-publish.XXXXXX")}; evidence_root=$test_root; current="$test_root/current"; lock_dir="$test_root/.verify.lock"; run_id=test; candidate="$test_root/.candidate"; staged="$test_root/.staged"; published_run="$test_root/runs/$run_id"; publish_link="$test_root/.current-$run_id"
  mkdir -p "$test_root/runs/old" "$candidate" "$staged" "$lock_dir"; printf old >"$test_root/runs/old/manifest.json"; printf new >"$candidate/manifest.json"; ln -s runs/old "$current"
  if publish_candidate; then echo 'forced publication failure unexpectedly succeeded' >&2; exit 1; fi
  move_failure_evidence; rm -rf "$staged" "$lock_dir"; if [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_PUBLISH_FAILURE}" = after-replace ]; then current_is_published && test "$(cat "$current/manifest.json")" = new && ! test -e "$publish_link" && ! test -e "$lock_dir"; else test "$(readlink "$current")" = runs/old && ! test -e "$candidate" && ! test -e "$published_run" && ! test -e "$publish_link" && test "$(cat "$test_root/failed-runs/test/manifest.json")" = new; fi
  echo "Analytics UI state ${RUSTZEN_ANALYTICS_UI_STATE_TEST_PUBLISH_FAILURE} publication seam passed"; [ -n "${RUSTZEN_ANALYTICS_UI_STATE_TEST_ROOT:-}" ] || rm -rf "$test_root"; exit 0
fi
if [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_STAGING_REPLACE:-}" = 1 ]; then
  test_root=$(mktemp -d "${TMPDIR:-/tmp}/rz-analytics-ui-state-staging.XXXXXX"); bin_dir="$test_root/bin"; candidate="$test_root/candidate"; staged="$test_root/staged"; file_pattern='.*'; mkdir -p "$bin_dir" "$candidate" "$staged"
  for name in rz-admin rz-monitor rz-insights rz-reports; do printf '%s-original\n' "$name" >"$bin_dir/$name"; chmod +x "$bin_dir/$name"; done
  { for name in rz-admin rz-monitor rz-insights rz-reports; do printf '%s\t%s\n' "$name" "$(shasum -a 256 "$bin_dir/$name" | awk '{print $1}')"; done; } >"$candidate/build-provenance.txt"
  stage_binary rz-admin; printf replacement >"$bin_dir/rz-monitor"; chmod +x "$bin_dir/rz-monitor"; if stage_binary rz-monitor; then echo 'concurrent replacement unexpectedly matched provenance' >&2; exit 1; fi
  rm -rf "$test_root"; echo 'Analytics UI state concurrent staging seam passed'; exit 0
fi
if [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_ARTIFACT_TAMPER:-}" = 1 ]; then
  test_root=$(mktemp -d "${TMPDIR:-/tmp}/rz-analytics-ui-state-artifact.XXXXXX"); candidate=$test_root; printf desktop >"$candidate/analytics-overview-desktop-dark-en.png"; printf mobile >"$candidate/analytics-details-mobile-light-zh.png"; printf '%s\n' '{"artifacts":[{"file":"analytics-overview-desktop-dark-en.png","sha256":"bad","dimensions":"1440 x 900"},{"file":"analytics-details-mobile-light-zh.png","sha256":"bad","dimensions":"390 x 844"}]}' >"$candidate/manifest.json"
  if verify_artifacts "$candidate/manifest.json"; then echo 'tampered artifact manifest unexpectedly verified' >&2; exit 1; fi; rm -rf "$test_root"; echo 'Analytics UI state artifact tamper seam passed'; exit 0
fi
if [ "${RUSTZEN_ANALYTICS_UI_STATE_TEST_STEP_RECEIPT_TAMPER:-}" = 1 ]; then
  test_root=$(mktemp -d "${TMPDIR:-/tmp}/rz-analytics-ui-state-steps.XXXXXX"); printf '%s\n' '{"case":[{"action":"goto"}]}' >"$test_root/expected.json"; printf '%s\n' '{"runSteps":{"case":[{"action":"goto","status":"succeeded","message":null}]}}' >"$test_root/manifest.json"; verify_step_receipts "$test_root/manifest.json" "$test_root/expected.json"
  printf '%s\n' '{"runSteps":{}}' >"$test_root/manifest.json"; if verify_step_receipts "$test_root/manifest.json" "$test_root/expected.json"; then echo 'omitted step receipt unexpectedly verified' >&2; exit 1; fi
  printf '%s\n' '{"runSteps":{"case":[{"action":"goto","status":"failed","message":"tampered"}]}}' >"$test_root/manifest.json"; if verify_step_receipts "$test_root/manifest.json" "$test_root/expected.json"; then echo 'tampered step receipt unexpectedly verified' >&2; exit 1; fi
  rm -rf "$test_root"; echo 'Analytics UI state step receipt omission and tamper seam passed'; exit 0
fi
if [ -n "${RUSTZEN_ANALYTICS_UI_STATE_TEST_MANIFEST:-}" ]; then
  test_manifest=$RUSTZEN_ANALYTICS_UI_STATE_TEST_MANIFEST; test_steps=${RUSTZEN_ANALYTICS_UI_STATE_TEST_BROWSER_STEPS:?missing browser steps}; read -r test_head test_state test_sha test_platform < <(jq -r '[.gitHead,.sourceTreeState,.sourceTreeSha256,.platform] | @tsv' "$test_manifest")
  verify_manifest "$test_manifest" "$test_steps" "$test_head" "$test_state" "$test_sha" "$test_platform"; echo 'Analytics UI state manifest verification seam passed'; exit 0
fi

validate_timeout "$timeout" RUSTZEN_ANALYTICS_UI_STATE_TIMEOUT 900; validate_timeout "$info_timeout" RUSTZEN_ANALYTICS_UI_STATE_DOCKER_INFO_TIMEOUT 60
architecture=${RUSTZEN_UI_LINUX_ARCH:-}; if [ -z "$architecture" ]; then architecture=$(run_bounded_capture "$info_timeout" "$docker_bin" info --format '{{.Architecture}}') || { echo 'Docker architecture discovery failed or timed out' >&2; exit 1; }; fi
case "$architecture" in aarch64) platform=linux/arm64; target_triple=aarch64-unknown-linux-musl; file_pattern='ELF 64-bit.*ARM aarch64';; x86_64) platform=linux/amd64; target_triple=x86_64-unknown-linux-musl; file_pattern='ELF 64-bit.*x86-64';; *) echo "unsupported Docker architecture: $architecture" >&2; exit 1;; esac
read -r verifier_image verifier_key verifier_provenance_sha < <("$root/scripts/ensure-admin-browser-verifier-image.sh" --platform "$platform")
bin_dir=${RUSTZEN_UI_LINUX_BIN_DIR:-"$root/target/rz/build/$architecture/bin"}; read -r head tree_state tree_sha < <("$root/scripts/admin-browser-source-identity.sh")
evidence_root="$root/target/rz/analytics-ui-state"; current="$evidence_root/current"; lock_dir="$evidence_root/.verify.lock"; run_id="$(date -u +%Y%m%dT%H%M%SZ)-$$"; candidate="$evidence_root/.candidate-$run_id"; staged="$evidence_root/.binaries-$run_id"; published_run="$evidence_root/runs/$run_id"; publish_link="$evidence_root/.current-$run_id"; container="rz-analytics-ui-state-$run_id"
cleanup() { local result=$?; trap - EXIT INT TERM; cleanup_bounded_processes; if [ -d "$candidate" ]; then "$docker_bin" logs "$container" >"$candidate/container.log" 2>&1 || true; fi; "$docker_bin" rm -f "$container" >/dev/null 2>&1 || true; rm -rf "$staged" "$publish_link"; if [ "$result" -ne 0 ]; then move_failure_evidence; fi; rm -rf "$lock_dir"; exit "$result"; }
mkdir -p "$evidence_root/runs"; if [ -e "$current" ] && [ ! -L "$current" ]; then echo 'refusing to replace legacy Analytics UI evidence directory' >&2; exit 1; fi; if ! mkdir "$lock_dir" 2>/dev/null; then echo "another Analytics UI state verification owns $lock_dir" >&2; exit 1; fi
trap cleanup EXIT; trap 'exit 130' INT; trap 'exit 143' TERM; mkdir -p "$candidate" "$staged"
test -s "$bin_dir/build-provenance.txt" || { echo 'missing build provenance' >&2; exit 1; }; cp "$bin_dir/build-provenance.txt" "$candidate/build-provenance.txt"
awk -F '\t' -v head="$head" -v state="$tree_state" -v sha="$tree_sha" -v arch="$architecture" -v triple="$target_triple" -v platform="$platform" '$1=="schemaVersion"&&$2=="1"{a=1} $1=="gitHead"&&$2==head{b=1} $1=="sourceTreeState"&&$2==state{c=1} $1=="sourceTreeSha256"&&$2==sha{d=1} $1=="architecture"&&$2==arch{e=1} $1=="targetTriple"&&$2==triple{f=1} $1=="platform"&&$2==platform{g=1} $1=="distribution"&&$2=="full"{h=1} END{exit !(a&&b&&c&&d&&e&&f&&g&&h)}' "$candidate/build-provenance.txt" || { echo 'Linux provenance does not match current source identity' >&2; exit 1; }
for name in rz-admin rz-monitor rz-insights rz-reports; do test -x "$bin_dir/$name" || { echo "missing Linux binary: $bin_dir/$name; run just build-admin-browser-linux" >&2; exit 1; }; stage_binary "$name" || { echo "staged Linux binary differs from immutable provenance: $name" >&2; exit 1; }; done
pnpm dlx bun@1.3.14 "$root/scripts/analytics-ui-state-browser-steps.mjs" >"$candidate/browser-steps.json"
run_bounded "$timeout" "$docker_bin" run --name "$container" --platform "$platform" --security-opt seccomp=unconfined --env RUSTZEN_VERIFY_HEAD="$head" --env RUSTZEN_VERIFY_SOURCE_TREE_STATE="$tree_state" --env RUSTZEN_VERIFY_SOURCE_TREE_SHA256="$tree_sha" --env RUSTZEN_VERIFY_PLATFORM="$platform" --env RUSTZEN_VERIFY_CHROMIUM_VERSION=120.0.6099.224-1~deb11u1 --mount "type=bind,src=$staged,dst=/verify/bin,readonly" --mount "type=bind,src=$candidate,dst=/verify/evidence" --mount "type=bind,src=$root/scripts/verify-analytics-ui-state-linux-inner.sh,dst=/verify/run.sh,readonly" --mount "type=bind,src=$root/scripts/analytics-ui-state-fixture.py,dst=/verify/fixture.py,readonly" "$verifier_image" bash /verify/run.sh
verify_manifest "$candidate/manifest.json" "$candidate/browser-steps.json" "$head" "$tree_state" "$tree_sha" "$platform"
verify_artifacts "$candidate/manifest.json"
read -r final_head final_state final_sha < <("$root/scripts/admin-browser-source-identity.sh"); test "$final_head" = "$head" && test "$final_state" = "$tree_state" && test "$final_sha" = "$tree_sha"
publish_candidate; rm -rf "$staged" "$lock_dir"; trap - EXIT INT TERM; echo "Analytics UI state Linux evidence published: $current/manifest.json"
