//! Exact notification configuration keys for the selected server activation.
pub(super) const ADMIN_NOTIFY_KEYS: &[&str] = &[
    "RUSTZEN_NOTIFICATION_CHARGED_BYTES_LIMIT",
    "RUSTZEN_NOTIFICATION_EVENT_KEY",
    "RUSTZEN_NOTIFICATION_EVENT_KEY_ID",
    "RUSTZEN_NOTIFICATION_FREE_SPACE_RESERVE_BYTES",
    "RUSTZEN_NOTIFICATION_INGRESS_PORT",
    "RUSTZEN_NOTIFICATION_MESSAGE_LIMIT",
    "RUSTZEN_NOTIFICATION_PREVIOUS_EVENT_KEY",
    "RUSTZEN_NOTIFICATION_PREVIOUS_EVENT_KEY_EXPIRES_AT",
    "RUSTZEN_NOTIFICATION_PREVIOUS_EVENT_KEY_ID",
    "RUSTZEN_NOTIFICATION_RECEIPT_LIMIT",
    "RUSTZEN_NOTIFICATION_RECIPIENT_LIMIT",
    "RUSTZEN_NOTIFICATION_WAL_PRESSURE_FRAMES",
    "RUSTZEN_NOTIFICATION_WAL_PRESSURE_OBSERVATIONS",
];
pub(super) const MONITOR_NOTIFY_KEYS: &[&str] = &[
    "RUSTZEN_NOTIFICATION_EVENT_KEY",
    "RUSTZEN_NOTIFICATION_EVENT_KEY_ID",
    "RUSTZEN_NOTIFICATION_INGRESS_URL",
];
