name: Frontend Build

on:
    workflow_dispatch:

env:
    NODE_VERSION: "24.2.0"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm install
              working-directory: ./web

            - name: Build project
              run: npm run build
              working-directory: ./web

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-dist
                  path: web/dist/
                  retention-days: 30
