name: Full Stack Build

on:
    workflow_dispatch:

env:
    NODE_VERSION: "24.2.0"
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # ---------- 前端构建 ----------
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install frontend dependencies
              run: npm install
              working-directory: ./web

            - name: Build frontend
              run: npm run build
              working-directory: ./web

            # ---------- 后端构建 ----------
            - name: Build backend
              run: cargo build --release

            # ---------- 上传构建产物 ----------
            - name: Upload full build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rustzen-admin
                  path: target/release/rustzen-admin
