name: Rust

on:
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build
              run: cargo build --release

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rustzen-admin
                  path: target/release/rustzen-admin
